#!/bin/sh
chown root:wheel /Library/LaunchDaemons/com.imokhles.developerslibfbdlaunch.plist
chmod 644 /Library/LaunchDaemons/com.imokhles.developerslibfbdlaunch.plist

chmod 4755 /usr/libexec/developerslibfb
chown root:wheel /usr/libexec/developerslibfb

launchctl load /Library/LaunchDaemons/com.imokhles.developerslibfbdlaunch.plist

exit 0